### ISSUE TITLE
Not Installing Under GRAV Beta Admin

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-readingtime#1]
FYI ... Plugin does not install under the new GRAV Beta Admin. I hand to install it the old fashion way (by hand), but even after that, it did not work correctly due to an "_" (underscore) in the folder name (Reading_Time) which I changed to "ReadingTime"; it works fine now. However, it still shows under the "Add" plugins list, meaning it doesn't think it is installed.

**Comment by rhukster** [comment]
Thanks I'll get this sorted.

**Comment by flaviocopes** [comment]
Looks like stored in the gpm as reading_time but here it's readingtime?

**Comment by ghost** [comment]
According to the installation instructions, it is suppose to be "readingtime" ...

> "The contents of the zipped folder should now be located in the /your/site/grav/user/plugins/readingtime directory."

Brian U.

**Comment by rhukster** [comment]
This should already be fixed.
