### ISSUE TITLE
Include time for images [feature request]

### ISSUE THREAD

**Issue by stephengmatthews** [getgrav/grav-plugin-readingtime#16]
I'm new to contributing. I've implemented a feature for this plugin that adds time to accommodate for users viewing images as well as reading text. The algorithm is simple and it's from [here](https://medium.com/blogging-guide/how-is-medium-article-read-time-calculated-924420338a85). The feature can be enabled/disabled from the yaml config. I've also updated the readme. I currently use it on my website.

I'd like to create a pull request with my changes. Is this feature inline with this repository? I was thinking it might be not considered if I had not discussed it before submitting a pull request,

Also, I noticed there's an older pull request (from January 2019) that made me think mine might not be considered.

What are your thoughts? Any help or nudges in the right direction would be great as I'm learning the process of contributing. Thanks!

**Comment by rhukster** [comment]
For the PR to be considered it needs to be complete (update to the readme if required, default yaml, blueprints etc.), it also needs to be backward compatible and not change existing behavior (ie updating the plugin adds new optional functionality, not change default behavior).  Also if you are using images or something that needs to be customizable to fit a theme, it needs to be easy to do so. Be it a configurable location for customized images, or an overridable twig were image refs can be changed etc.  again needs to be documented. 

Any feature that is fully thought out and developed I have no issue merging. :)
