### ISSUE TITLE
word_per_minute is not defined in blueprints

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-readingtime#2]
Hello,

I installed the plugin successfully but after enabled it I get the error "Validation failed: word_per_minute is not defined in blueprints".
Do you have any idea how to resolve this?
Thank you in advance!

P.S.: Running Grav v1.0.10 with the Multilang (cacti) skeleton theme.

**Comment by rhukster** [comment]
I guess the blueprints never got updated to reflect the fields. I'll get this fixed up and rerelease it.

**Comment by rhukster** [comment]
Fixed in last release.
