### ISSUE TITLE
Rounding to minutes messes up plural/singular

### ISSUE THREAD

**Issue by ohnonot** [getgrav/grav-plugin-readingtime#5]
I am happy to estimate reading time in minutes (without seconds), but the plugin rounds e.g. 
"0 minutes 40 seconds" to "1 minutes"
"1 minute 45 seconds" to "2 minute"
and so on.

PS:
I have seen [issue nr 3](https://github.com/getgrav/grav-plugin-readingtime/issues/3).

**Comment by jimblue** [comment]
Same problem here.
1 minutes is plural should be singular.

**Comment by jimblue** [comment]
Thanks @flaviocopes for the update... fixed!
